# CircleCI configuration for the Richard's blog
version: 2.1

aliases:
  # Cache management
  - &restore-npm-cache
    keys:
      - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-deps-{{ .Branch }}
      - v1-deps

  - &save-npm-cache
    key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
    # cache NPM modules and the folder with the Cypress binary
    paths:
      - ~/.npm
      - ~/.cache

  - &start-web
    name: start web client in the background
    command: npm run develop
    background: true

defaults: &defaults
  working_directory: ~/therichardblog

js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:12.14.0

jobs:
  checkout_environment:
    <<: *js_defaults
    steps:
      - checkout

      - restore_cache: *restore-npm-cache
      - run: npm ci
      - save_cache: *save-npm-cache

      - persist_to_workspace:
          root: .
          paths: .

  test_unit:
    <<: *defaults
    docker:
      - image: circleci/node:12.14.0
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/therichardblog
      - run: npm run test

  test_e2e:
    <<: *defaults
    docker:
      - image: circleci/node:12.14.0-browsers
      - image: cypress/base:14.16.0
    parameters:
      parallelism:
        type: integer
        default: 1
        description: Number of boxes to use to run this job

    parallelism: <<parameters.parallelism>>
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/therichardblog
      - run: *start-web
      - run:
          name: Install Cypress
          command: npm run cy:install
      - run:
          name: Run E2E Tests
          command: |
            if [ $CYPRESS_RECORD_KEY ]; then
              npm run test:e2e -- --record --parallel
            else
              npm run test:e2e
            fi

  build:
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    steps:
      - checkout

      - attach_workspace:
          at: ~/therichardblog
      - restore_cache: *restore-npm-cache
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install netlify-cli
          command: npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./public -p

workflows:
  test:
    jobs:
      - checkout_environment
      - test_unit:
          requires:
            - checkout_environment
      - test_e2e:
          requires:
            - checkout_environment

      - build:
          requires:
            - test_unit
            - test_e2e

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
